typography_spectrum: 0.956901378929615
color:
  brandStrength: 0.9326073764823377
  lightness: 0.07602139818482101
  saturation: 0.8843370941467583
  rhythmicContrast: 0.36676578130573034
  brandColors:
    - '#FF5335'
    - '#B39C85'
    - '#306E73'
    - '#3B424D'
    - '#1D181F'
layout_spectrum: 0.49150183447636664
name: Dental Implants in Bristol
navigation:
  - name: Dental implants in Bristol
    id: 0bc69fd8-7470-498d-af96-e075da861df2
    type: content
  - name: Bristol Clinic
    url: 'http://ckdental.co.uk'
    type: external
  - name: 'Price Guide '
    id: 4e2c9f66-78a7-4855-aa66-877fd77369ca
    type: content
title: Dental Implants in Bristol
description: Experts at your doorstep
